Vagrant.configure("2") do |config|
  config.ssh.host = "127.0.0.1"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.hostname = "docker-playground"
  config.vm.network :forwarded_port, id: 'ssh', guest: 22, host: 2200, auto_correct: false
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm_docker-playground"
    vb.cpus = 2
    vb.memory = 1024
  end
  config.vm.provision "shell", inline: <<-SHELL.gsub(/^ +/, '')
    echo "****************************** Configuring system settings"
    sudo timedatectl set-timezone Europe/Rome
    sudo update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
    echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
    echo "****************************** Downloading packages"
    sudo printf 'Acquire {http::User-Agent "Mozilla/5.0 (Windows NT 5.1; rv:25.0) Gecko/20100101 Firefox/25.0";};' > /etc/apt/apt.conf
    sudo aptitude -q -y update
    sudo aptitude -q -y upgrade
    sudo aptitude -q -y dist-upgrade
    sudo aptitude -q -y install sysv-rc-conf git tree whois unzip linux-kernel-headers
    echo "****************************** Updating Guest Additions"
    sudo wget -q -c http://download.virtualbox.org/virtualbox/LATEST.TXT -O /tmp/vbga-latest-version.txt
    vbgaLatestVersion=$(cat /tmp/vbga-latest-version.txt)
    sudo rm /tmp/vbga-latest-version.txt
    sudo wget -q -c http://download.virtualbox.org/virtualbox/$vbgaLatestVersion/VBoxGuestAdditions_$vbgaLatestVersion.iso -O vbga.iso
    sudo mount vbga.iso -o loop /mnt
    sudo sh /mnt/VBoxLinuxAdditions.run -- force
    sudo umount /mnt
    sudo rm vbga.iso
    sudo sysv-rc-conf vboxadd on
    echo "****************************** Installing Docker"
    sudo -i <<HEREDOC
      if ! docker version &>/dev/null; then
        echo "*** Installing Docker Engine"
        wget -qO- https://get.docker.com/ | bash
        usermod -aG docker vagrant
      fi
      if ! docker-compose --version &>/dev/null; then
        echo "Docker Compose"
        curl --silent -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      fi
    HEREDOC
  SHELL
end
